name: rec
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro/
  - defaults
dependencies:
  - blas=1.0=mkl
  - bottleneck=1.3.7=py312he558020_0
  - brotli=1.0.9=h2bbff1b_8
  - brotli-bin=1.0.9=h2bbff1b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.7.2=haa95532_0
  - cairo=1.18.0=h32b962e_3
  - chardet=4.0.0=py312haa95532_1003
  - contourpy=1.2.0=py312h59b6b97_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - expat=2.6.3=h5da7b33_0
  - font-ttf-dejavu-sans-mono=2.37=0
  - font-ttf-inconsolata=2.000=0
  - font-ttf-source-code-pro=2.030=0
  - font-ttf-ubuntu=0.83=0
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.51.0=py312h2bbff1b_0
  - freetype=2.12.1=hdaf720e_2
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - greenlet=3.0.1=py312hd77b12b_0
  - icu=75.1=he0c23c2_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - kiwisolver=1.4.4=py312hd77b12b_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=h67d730c_0
  - lerc=4.0.0=h63175ca_0
  - libboost=1.84.0=h444863b_6
  - libboost-python=1.84.0=py312hbaa7e33_6
  - libbrotlicommon=1.0.9=h2bbff1b_8
  - libbrotlidec=1.0.9=h2bbff1b_8
  - libbrotlienc=1.0.9=h2bbff1b_8
  - libdeflate=1.21=h2466b09_0
  - libexpat=2.6.3=he0c23c2_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.80.3=h7025463_2
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.3=h827c3e9_0
  - libpng=1.6.44=h3ca93ac_0
  - libpq=16.4=hab9416b_1
  - librdkit=2024.03.5=h4c5bbc8_3
  - libsqlite=3.46.1=h2466b09_0
  - libtiff=4.6.0=hb151862_4
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.16=h013a479_1
  - libzlib=1.3.1=h2466b09_1
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-base=3.9.2=py312hbdc63d0_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h2bbff1b_1
  - mkl_fft=1.3.10=py312h827c3e9_0
  - mkl_random=1.2.7=py312h0158946_0
  - msys2-conda-epoch=20160418=1
  - numexpr=2.8.7=py312h96b7d27_0
  - numpy-base=1.26.4=py312h4dde369_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.3.2=h2466b09_0
  - packaging=24.1=py312haa95532_0
  - pandas=2.2.2=py312h0158946_0
  - pcre2=10.44=h3d7b363_2
  - pip=24.2=py312haa95532_0
  - pixman=0.43.4=h63175ca_0
  - pthread-stubs=0.3=h3c9f919_1
  - pycairo=1.27.0=py312h487989a_0
  - python=3.12.5=h889d299_0_cpython
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=5_cp312
  - pytz=2024.1=py312haa95532_0
  - rdkit=2024.03.5=py312h9d9823f_3
  - reportlab=4.2.2=py312h4389bb4_1
  - rlpycairo=0.2.0=pyhd8ed1ab_0
  - setuptools=72.1.0=py312haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlalchemy=2.0.34=py312h54f65d0_0
  - sqlite=3.45.3=h2bbff1b_0
  - tbb=2021.8.0=h59b6b97_0
  - tk=8.6.13=h5226925_1
  - typing_extensions=4.11.0=py312haa95532_0
  - tzdata=2024a=h04d1e81_0
  - ucrt=10.0.20348.0=haa95532_0
  - unicodedata2=15.1.0=py312h2bbff1b_0
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.40.33810=ha82c5b3_21
  - vs2015_runtime=14.40.33810=h3bf8584_21
  - wheel=0.44.0=py312haa95532_0
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.4.6=h8cc25b3_1
  - zlib=1.3.1=h2466b09_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - absl-py==2.1.0
      - aiohappyeyeballs==2.4.0
      - aiohttp==3.10.5
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - asttokens==2.4.1
      - attrs==24.2.0
      - bibtexparser==1.4.3
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - chex==0.1.87
      - colorama==0.4.6
      - comm==0.2.2
      - debugpy==1.8.7
      - decorator==5.1.1
      - dgl==2.2.1+cu121
      - etils==1.10.0
      - executing==2.1.0
      - fake-useragent==1.5.1
      - filelock==3.16.1
      - flax==0.10.2
      - frozenlist==1.4.1
      - fsspec==2024.9.0
      - future==1.0.0
      - grpcio==1.66.2
      - huggingface-hub==0.26.2
      - humanize==4.11.0
      - idna==3.10
      - importlib-resources==6.4.5
      - ipykernel==6.29.5
      - ipython==8.28.0
      - jax==0.4.35
      - jaxlib==0.4.35
      - jedi==0.19.1
      - jinja2==3.1.4
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - lightning==2.4.0
      - lightning-utilities==0.11.7
      - loguru==0.7.2
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - nest-asyncio==1.6.0
      - networkx==3.3
      - numpy==1.26.0
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.10.1
      - parso==0.8.4
      - pillow==11.0.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.48
      - protobuf==5.28.2
      - psutil==6.0.0
      - pure-eval==0.2.3
      - pydantic==2.9.2
      - pydantic-core==2.23.4
      - pygments==2.18.0
      - pyparsing==3.1.4
      - pytorch-lightning==1.2.6
      - pywin32==308
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - safetensors==0.4.5
      - scikit-learn==1.5.2
      - scipy==1.11.3
      - simplejson==3.19.3
      - stack-data==0.6.3
      - sympy==1.13.1
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorstore==0.1.69
      - threadpoolctl==3.5.0
      - tokenizers==0.20.4
      - toolz==1.0.0
      - torch==2.2.0+cu121
      - torch-geometric==2.6.0
      - torch-scatter==2.1.2+pt22cu121
      - torchdata==0.7.1
      - torchmetrics==1.4.2
      - torchvision==0.17.0
      - tornado==6.4.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - transformers==4.46.3
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - werkzeug==3.0.4
      - win32-setctime==1.1.0
      - yarl==1.11.1
      - zipp==3.21.0
prefix: D:\Anaconda\envs\rec
